### ISSUE TITLE
blogAuthors treated as blogAdmins

### ISSUE THREAD

**Issue by MichaelSolati** [meteor-blog/meteor-blog#197] opened 2015-07-15 15:02 UTC
Ok, so I have ryw:blog added to my Meteor app. And I’m trying to set everyone to have an author role when created with the following code…

```javascript
Accounts.onCreateUser(function (options, user) {
     user.roles = ['blogAuthor'];
     if (options.profile)
     user.profile = options.profile;
     return user;
});
```

So now I need to enable both roles, by specify values in the blog config. But I’m not sure where that should be! If I keep the code below…

```javascript
if (Meteor.isServer) {
     Blog.config({
          adminRole: 'blogAdmin',
          authorRole: 'blogAuthor'
     });
}
```

In my server folder, only people with the role “blogAdmin” and/or “blogAuthor” can post in the blog, but no matter what the role, they are treated as an admin! Any help here would be appreciated.

**Comment by hellogerard** [comment] 2015-07-20 15:13
I'm not sure I completely understand the issue. Are  you saying that if you have a user that has _only_ the `blogAuthor` role, he or she is treated as an admin (i.e. can modify other users' blog posts)? If so, that is a bug.

**Comment by MehdiSolati** [comment] 2015-07-20 20:45
Yes, that's exactly what I mean. Then again, I may be doing something wrong, but that's the situation I'm in.

**Comment by hellogerard** [comment] 2015-08-03 14:51
Still can't replicate this. What happens if you don't set an `adminRole`?

**Comment by MehdiSolati** [comment] 2015-08-24 22:17
If I set just an author role they would be treated as an author. Here's what I ended up finding out, and this may have been specific to something else I did during my project.

The documentation said that I just needed to configure my server code with this bit

```javascript
// JavaScript
if (Meteor.isServer) {
  Blog.config({
    adminRole: 'blogAdmin',
    authorRole: 'blogAuthor'
  });
}
```

Buuut, by breaking it up into two Blog.configs (like sooo)

```javascript
// JavaScript
if (Meteor.isServer) {
  Blog.config({
    adminRole: 'blogAdmin'
  });
}
if (Meteor.isServer) {
  Blog.config({
    authorRole: 'blogAuthor'
  });
}
```

The two roles worked just fine, without having the Author's having the same control/permissions as an Admin.

**Comment by hellogerard** [comment] 2015-10-02 21:44
Odd. Doesn't make any sense to me. Can you make a small repo that reproduces the bug and put it on Github?

**Comment by hellogerard** [comment] 2016-04-14 15:52
I believe that this is a dupe of #253. Closing this one and tracking there.

**Closed by hellogerard** 2016-04-14 15:52 UTC
Labels: bug, duplicate
